version: '3.8'

services:
  bot:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=xocPen-zijfe5-wydgor
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/data:/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
